#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = [
    'id' => 'yii2-debug',
    'basePath' => __DIR__ . '/tests/app',
];

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
