---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: build

permissions:
  contents: read

jobs:
  phpunit:
    uses: yiisoft/yii2-actions/.github/workflows/phpunit.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      extensions: gd, intl
      php-version: '["8.3","8.4","8.5"]'
